name: Run Tests

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/cache@v2
      with:
        path: |
          .yarn/cache
        key: node-${{ hashFiles('yarn.lock') }}
    - name: Install and Link Packages
      run: |
        yarn install
      env:
          YARN_CHECKSUM_BEHAVIOR: update
    - name: Run Tests
      run: yarn test
    - name: Upload Coverage
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Lint Code
      run: yarn lint
